language: csharp
sudo: false
mono: none
dotnet: 2.0.0
dist: xenial
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

os:
  - linux

script:
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore -r ubuntu.16.04-x64; fi
  - dotnet build -c Release
