language: csharp
sudo: false
mono: none
dotnet: 2.0.0
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

os:
  - linux
  - osx

osx_image: xcode8.3
script:
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore -c Release -r ubuntu.14.04-x64; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
