language: csharp
sudo: false
mono: none
dotnet: 2.0.0
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

os:
  - linux

script:
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore -r ubuntu.14.04-x64; fi
  - dotnet build -c Release
  - cd $TEST_PATH
  - dotnet add ./$TEST_PROJECT package xunit.runner.console --version 2.3.0-beta5-build3769
  - dotnet restore ./$TEST_PROJECT -r ubuntu.14.04-x64
  - dotnet build ./$TEST_PROJECT -c Release
